# Generated by Django 2.2 on 2020-03-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
    ]
